version: '3'

services:

## Setup server container ##
  server:
    build: ./server
    container_name: "pathfinder-server"
    expose:
      - ${APP_SERVER_PORT}
    environment:
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/models:/srv/app/pathfinder-server/models
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm run start 


## Setup client container ##
  client:
    build: ./client
    container_name: "pathfinder-client"
    expose:
      - ${VUE_APP_PORT}
    environment:
      - VUE_APP_PORT=${VUE_APP_PORT}
    ports:
      - ${VUE_APP_PORT}:${VUE_APP_PORT}
    volumes:
      - ./client/src:/srv/app/pathfinder-client/src
    links:
      - server
    command: npm run dev


## Setup mongodb container ##
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
      - ./data/log:/data/log
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet